apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-frontend
  namespace: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}-frontend
spec:
  replicas: {{ .Values.app.frontend.replica }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-frontend
    spec:
      containers:
      - name: {{ .Values.app.name }}-frontend
        image: {{ .Values.app.frontend.image }}:{{ .Values.app.frontend.tag }}
        ports:
        - containerPort: {{ .Values.app.frontend.service.port }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.frontend.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.frontend.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi