apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
  namespace: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}-frontend
  type: {{ .Values.app.frontend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.frontend.service.port }}
      targetPort: {{ .Values.app.frontend.port }}