apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-backend
  namespace: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}-backend
  type: {{ .Values.app.backend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.backend.service.port }}
      targetPort: {{ .Values.app.backend.port }}